// Generated by backend/scripts/generate_sandbox_outcomes.py — do not edit by hand.
// Re-run the script when the scene, its plan or the tour disruption changes.
import { SandboxOutcomes } from './sandbox-outcomes';

export const SANDBOX_OUTCOMES: SandboxOutcomes = {
  "scenario": "pf-ch-wn-wal-long-approach",
  "generator": "backend/scripts/generate_sandbox_outcomes.py",
  "generatedOn": "2026-09-15",
  "planArrivalSteps": {
    "0": 57,
    "1": 63,
    "2": 57
  },
  "cases": [
    {
      "id": "experienced-single-track",
      "kind": "experienced",
      "title": "{T0} bleibt im Einspurabschnitt stehen",
      "situation": "Der Vorfall aus deiner Schicht: {T0} steht ab Schritt 28 für 12 Schritte mitten im einspurigen Abschnitt, {T1} folgt auf demselben Gleis.",
      "decisionHandle": 1,
      "decisionStep": 28,
      "variants": [
        {
          "id": "hold-release",
          "label": "Halten, dann freigeben",
          "description": "{T1} wartet, bis {T0} wieder fährt, und wird dann freigegeben.",
          "matchesAction": "hold",
          "arrived": 3,
          "total": 3,
          "totalDelayVsPlan": 30,
          "trains": [
            {
              "handle": 0,
              "arrived": true,
              "arrivalStep": 69,
              "delayVsPlan": 12
            },
            {
              "handle": 1,
              "arrived": true,
              "arrivalStep": 72,
              "delayVsPlan": 9
            },
            {
              "handle": 2,
              "arrived": true,
              "arrivalStep": 66,
              "delayVsPlan": 9
            }
          ]
        },
        {
          "id": "proceed",
          "label": "Weiterfahren",
          "description": "{T1} fährt weiter bis vor die Störung und wartet dort.",
          "matchesAction": "proceed",
          "arrived": 3,
          "total": 3,
          "totalDelayVsPlan": 26,
          "trains": [
            {
              "handle": 0,
              "arrived": true,
              "arrivalStep": 69,
              "delayVsPlan": 12
            },
            {
              "handle": 1,
              "arrived": true,
              "arrivalStep": 70,
              "delayVsPlan": 7
            },
            {
              "handle": 2,
              "arrived": true,
              "arrivalStep": 64,
              "delayVsPlan": 7
            }
          ]
        },
        {
          "id": "hold-no-release",
          "label": "Halten ohne Freigabe",
          "description": "{T1} bleibt angehalten, weil niemand die Freigabe gibt.",
          "matchesAction": null,
          "arrived": 1,
          "total": 3,
          "totalDelayVsPlan": 12,
          "trains": [
            {
              "handle": 0,
              "arrived": true,
              "arrivalStep": 69,
              "delayVsPlan": 12
            },
            {
              "handle": 1,
              "arrived": false,
              "arrivalStep": null,
              "delayVsPlan": null
            },
            {
              "handle": 2,
              "arrived": false,
              "arrivalStep": null,
              "delayVsPlan": null
            }
          ]
        }
      ]
    },
    {
      "id": "novel-head-on",
      "kind": "novel",
      "title": "Gegenzug vor dem blockierten Einspurabschnitt",
      "situation": "Nicht erlebt: {T1} bleibt ab Schritt 34 für 20 Schritte im Einspurabschnitt stehen, während {T2} aus der Gegenrichtung auf den Abschnitt zufährt.",
      "decisionHandle": 2,
      "decisionStep": 34,
      "variants": [
        {
          "id": "hold-release",
          "label": "{T2} halten, dann freigeben",
          "description": "{T2} wartet vor dem Abschnitt, bis {T1} ihn räumt.",
          "matchesAction": "hold",
          "arrived": 3,
          "total": 3,
          "totalDelayVsPlan": 40,
          "trains": [
            {
              "handle": 0,
              "arrived": true,
              "arrivalStep": 57,
              "delayVsPlan": 0
            },
            {
              "handle": 1,
              "arrived": true,
              "arrivalStep": 83,
              "delayVsPlan": 20
            },
            {
              "handle": 2,
              "arrived": true,
              "arrivalStep": 77,
              "delayVsPlan": 20
            }
          ]
        },
        {
          "id": "proceed",
          "label": "{T2} weiterfahren lassen",
          "description": "{T2} fährt bis an die Einfahrt und wartet dort.",
          "matchesAction": "proceed",
          "arrived": 3,
          "total": 3,
          "totalDelayVsPlan": 40,
          "trains": [
            {
              "handle": 0,
              "arrived": true,
              "arrivalStep": 57,
              "delayVsPlan": 0
            },
            {
              "handle": 1,
              "arrived": true,
              "arrivalStep": 83,
              "delayVsPlan": 20
            },
            {
              "handle": 2,
              "arrived": true,
              "arrivalStep": 77,
              "delayVsPlan": 20
            }
          ]
        },
        {
          "id": "reroute",
          "label": "{T2} umleiten",
          "description": "{T2} nimmt die von der KI angebotene Umfahrung.",
          "matchesAction": "reroute",
          "arrived": 0,
          "total": 3,
          "totalDelayVsPlan": 0,
          "trains": [
            {
              "handle": 0,
              "arrived": false,
              "arrivalStep": null,
              "delayVsPlan": null
            },
            {
              "handle": 1,
              "arrived": false,
              "arrivalStep": null,
              "delayVsPlan": null
            },
            {
              "handle": 2,
              "arrived": false,
              "arrivalStep": null,
              "delayVsPlan": null
            }
          ]
        }
      ]
    }
  ]
};
